version: "3.9"
services:
  web:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./website:/var/www/html
    ports:
      - 8080:8080
    depends_on:
      - scrapy
  scrapy:
    build: 
      context: ./sreality
      dockerfile: ./Dockerfile
    volumes:
      - ./sreality:/usr/src/sreality/
    ports:
      - 8000:5000
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lana
      - POSTGRES_PASSWORD=luxonis
      - POSTGRES_DB=estates
      - POSTGRES_HOST=localhost
volumes:
  postgres_data:
